---
MainSourceFile:  '/mnt/workdisk/public_share/nyacore-workspace/nekocode-cpp-github/tidy_test.yaml'
Diagnostics:
  - DiagnosticName:  clang-diagnostic-error
    DiagnosticMessage:
      Message:         'unable to handle compilation, expected exactly one compiler job in '''''
      FilePath:        ''
      FileOffset:      0
      Replacements:    []
    Level:           Error
    BuildDirectory:  ''
...
